# Generated by Django 3.2.3 on 2021-06-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
