# Generated by Django 3.2.3 on 2021-06-08 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pra', '0003_auto_20210608_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tinestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
