# Generated by Django 3.2.4 on 2021-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=30)),
                ('subject', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80)),
                ('email', models.TextField(max_length=30)),
                ('email2', models.TextField(max_length=30)),
                ('call', models.CharField(max_length=15)),
                ('call2', models.CharField(max_length=15)),
            ],
        ),
    ]
