# Generated by Django 3.2.3 on 2021-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=30)),
                ('subject', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
