# Generated by Django 3.2.3 on 2021-05-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80)),
                ('email', models.TextField(max_length=30)),
                ('email2', models.TextField(max_length=30)),
                ('call', models.CharField(max_length=15)),
                ('call2', models.CharField(max_length=15)),
            ],
        ),
    ]
