# Generated by Django 3.2.3 on 2021-05-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('photo', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=900),
        ),
    ]
