# Generated by Django 3.2.4 on 2021-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='endfooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=50)),
                ('designed', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('teitter', models.CharField(max_length=50)),
                ('linkden', models.CharField(max_length=50)),
                ('instragram', models.CharField(max_length=50)),
            ],
        ),
    ]
